name: 'Auto Assign'
on:
  pull_request:
    types: [opened]

jobs:
  add-reviews:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write
    steps:
      - name: Auto Assign
        uses: kentaro-m/auto-assign-action@v2.0.0
